- hosts: localhost
  connection: local
  become: yes

  vars:
    kubectx_project: ahmetb/kubectx
    kubectx_dir: /opt/kubectx

  tasks:

    - name: KUBECTL - get the username
      become: false
      command: whoami
      register: whoami_output

    - name: KUBECTL - add key
      apt_key:
        url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
        state: present

    - name: KUBECTL - add kubernetes repo
      apt_repository:
        repo: deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main
        filename: kubernetes
        state: present

    - name: KUBECTL - install kubectl
      apt:
        name: kubectl
        state: present

    - name: KUBECTL - install bash-completion (apt)
      apt:
        name: bash-completion
        state: present

    - name: KUBECTL - activate auto-completion for kubectl
      shell: kubectl completion bash >/etc/bash_completion.d/kubectl

    - name: KUBCTL - create kubectx directory
      file:
        path: "{{ kubectx_dir }}"
        state: directory

    - name: KUBECTL - Get latest release
      uri:
        url: "https://api.github.com/repos/{{ kubectx_project }}/releases/latest"
        return_content: yes
      register: kubectx_release

    - name: KUBECTL - View latest release
      debug:
        msg: "{{ kubectx_release.json.tag_name }}"

    - name: KUBECTL - Download and extract kubectx and kubens
      unarchive:
        src: "{{ item }}"
        dest: "{{ kubectx_dir }}"
        remote_src: yes
      with_items:
        - "https://github.com/{{ kubectx_project }}/releases/download/{{ kubectx_release.json.tag_name }}/kubectx_{{ kubectx_release.json.tag_name }}_linux_x86_64.tar.gz"
        - "https://github.com/{{ kubectx_project }}/releases/download/{{ kubectx_release.json.tag_name }}/kubens_{{ kubectx_release.json.tag_name }}_linux_x86_64.tar.gz"

    - name: KUBECTL - Make kubectx and kubens executable
      file:
        path: "{{ kubectx_dir }}/{{ item }}"
        mode: 0755
      with_items:
        - "kubectx"
        - "kubens"

    - name: KUBECTL - Create kubectx and kubens link
      file:
        src: "{{ kubectx_dir }}/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        state: link
      with_items:
        - "kubectx"
        - "kubens"

    - name: KUBECTL - check OH-MY-ZSH
      stat:
        path: "/home/{{ whoami_output.stdout }}/.oh-my-zsh"
      register: ohmyzsh

    - block:

      - name: KUBECTL - create ZSH completions directory
        become: false
        file:
          path: /home/{{ whoami_output.stdout }}/.oh-my-zsh/completions
          state: directory
          mode: 0755

      - name: KUBECTL - Create kubectx and kubens ZSH completion link
        become: false
        file:
          src: "{{ kubectx_dir }}/git/completion/_{{ item }}.zsh"
          dest: "/home/{{ whoami_output.stdout }}/.oh-my-zsh/completions/_{{ item }}.zsh"
          state: link
        with_items:
          - "kubectx"
          - "kubens"

      when: ohmyzsh.stat.isdir is defined and ohmyzsh.stat.isdir

    - name: KUBECTL - install pkg-config
      become: yes
      apt:
        name: pkg-config
        state: present

    - name: KUBECTL - get bash completion directory
      shell: >-
        pkg-config --variable=completionsdir bash-completion
      register: completionsdir

    - name: KUBECTL - Create kubectx and kubens bash completion link
      file:
        src: "{{ kubectx_dir }}/git/completion/{{ item }}.bash"
        dest: "{{ completionsdir.stdout }}/{{ item }}"
        state: link
      with_items:
        - "kubectx"
        - "kubens"
